apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  finalizers:
  - finalizers.fluxcd.io
  name: prometheus
  namespace: prometheus
spec:
  chart:
    spec:
      chart: prometheus
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: 25.8.0
  interval: 1m0s
  values:
    prometheus:
      ingress:
        enabled: true
        hosts:
        - prometheus.k8s.likens.us
        ingressClassName: nginx
      persistentVolume:
        enabled: true
      podSecurityPolicy:
        enabled: true
      rbac:
        create: true
