apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  finalizers:
  - finalizers.fluxcd.io
  name: prometheus-community
  namespace: prometheus
spec:
  interval: 1m0s
  provider: generic
  timeout: 60s
  url: https://prometheus-community.github.io/helm-charts
